platform=android
appiumServer=http://127.0.0.1:4723

android.udid=4c039a0d
android.deviceName=Pixel_6

android.appPackage=com.yokara.v3
android.appActivity=com.yokara.v3.MainActivity

ios.bundleId=com.yokara